Repository slub/dfg-viewer, pull requests merged in 2023-11, with the labels that each got.

#249 Move phpstan configuration to the correct directory
  .github/phpstan.neon
  .github/workflows/phpstan.yml
Labels: 🛠️ maintenance

#250 Fix DOM text reinterpreted as HTML in dfgviewerScripts.js
  Resources/Private/JavaScript/dfgviewerScripts.js
  Resources/Public/JavaScript/allScripts.js
Labels: ⚡ security

#251 Fix DOM text reinterpreted as HTML in dfgviewerSru.js
  Resources/Private/JavaScript/dfgviewerSru.js
Labels: ⚡ security

#255 Fix call to `\Kitodo\Dlf\Middleware\SruMiddleware`
  Configuration/RequestMiddlewares.php
Labels: :bug: bug

#256 Add missing config for `titleReplacement`
  Configuration/TypoScript/Plugins/kitodo.typoscript
Labels: :bug: bug

#261 Grunt action to verify if compiled files are up to date
  .github/workflows/npm-grunt.yml
  Resources/Public/JavaScript/allScripts.js
Labels: 🛠️ maintenance
