Repository slub/dfg-viewer, pull requests merged in 2024-08, with the labels that each got.

#297 [BUGFIX] Fix distorted provider logo
  Resources/Private/Less/structure.less
  Resources/Public/Css/allStyles.css
  Resources/Public/Css/webStyles.css
Labels: :bug: bug

#304 Update Node JS
  .github/workflows/npm-grunt.yml
  .github/workflows/phpstan.yml
  .gitignore
  Build/package.json
Labels: 🛠️ maintenance

#305 Fix distorted provider logo
  Resources/Private/Less/structure.less
  Resources/Public/Css/allStyles.css
  Resources/Public/Css/webStyles.css
Labels: :bug: bug, 🛠️ maintenance

#295 [FEATURE] Migration to the changed 3d viewer implementation of Kitodo.Presentation
  Configuration/TypoScript/Page/header.typoscript
  Configuration/TypoScript/Plugins/kitodo.typoscript
  Resources/Private/Less/components/controls.less
  Resources/Private/Partials/ControlBar.html
  Resources/Private/Partials/PageView.html
  Resources/Private/Partials/Submenu.html
  Resources/Public/Css/3DViewer/main.css
  Resources/Public/Css/3DViewer/spinner.css
  Resources/Public/Css/allStyles.css
Labels: :heavy_check_mark: feature

#309 [MAINTENANCE] Add Maintainer to README
  README.md
Labels: 🛠️ maintenance

#310 [BUGFIX] Display labels for document types in ToC plugin
  Resources/Private/Less/modules/sidebar.less
  Resources/Public/Css/allStyles.css
Labels: :bug: bug

#311 Update versions for release 6.1.1
  composer.json
  ext_emconf.php
Labels: :link: dependency
