Repository slub/dfg-viewer, pull requests merged in 2025-02, with the labels that each got.

#337 [DEPENDENCY] Update Kitodo.Presentation to 5.1
  composer.json
Labels: :link: dependency

#336 [FEATURE] Toggle metadata, toc and metadata subentries
  Resources/Private/JavaScript/dfgviewerScripts.js
  Resources/Private/Less/all.less
  Resources/Private/Less/components/audioplayer.less
  Resources/Private/Less/components/controls.less
  Resources/Private/Less/components/sru.less
  Resources/Private/Less/modules/home.less
  Resources/Private/Less/modules/sidebar.less
  Resources/Private/Less/structure.less
  Resources/Private/Partials/ControlBar.html
  Resources/Public/Css/allStyles.css
  Resources/Public/Css/webStyles.css
  Resources/Public/Images/controlIcons.svg
  Resources/Public/JavaScript/allScripts.js
Labels: :heavy_check_mark: feature

#339 [DEPENDENCY] Update versions for release 6.3
  composer.json
  ext_emconf.php
Labels: :link: dependency

#323 [FEATURE] Workflow and functionalities to provide DFG-Viewer as a Docker image and use it
  .github/scripts/test-image.sh
  .github/workflows/build-test-publish.yml
  .gitignore
  Docker/.env.example
  Docker/README.md
  Docker/build/Dockerfile
  Docker/build/apache2-dfg-viewer.conf
  Docker/build/extensions/.gitkeep
  Docker/build/site/dfgviewer/config.yaml
  Docker/build/startup.sh
  Docker/build/wait-for-it.sh
  Docker/docker-compose.yml
Labels: :heavy_check_mark: feature

#322 [MAINTENANCE] Update to TYPO3 12
  .github/workflows/phpstan.yml
  Classes/Controller/SruController.php
  Classes/Controller/UriController.php
  Classes/Middleware/SruMiddleware.php
  Classes/ViewHelpers/CalendarDataVariableViewHelper.php
  Classes/ViewHelpers/TitleTagViewHelper.php
  Configuration/Services.yaml
  Configuration/TCA/Overrides/pages.php
  Configuration/TCA/Overrides/sys_template.php
  Configuration/TCA/Overrides/tt_content.php
  Configuration/TsConfig/Page.tsconfig
  Configuration/TypoScript/Navigation/language.typoscript
  Configuration/TypoScript/Page/header.typoscript
  Configuration/TypoScript/Page/page.typoscript
  Configuration/TypoScript/setup.typoscript
  Documentation/Index.rst
  Initialisation/Site/dfg-viewer/config.yaml
  Initialisation/data.xml
  Resources/Private/Less/structure.less
  Resources/Private/Less/website/header.less
  Resources/Private/Plugins/Dfgviewer/Templates/Uri/Main.html
  Resources/Private/Plugins/News/Faq/Templates/News/Detail.html
  Resources/Public/Css/allStyles.css
  Resources/Public/Css/webStyles.css
  Resources/Public/Icons/Extension.png
  composer.json
  ext_emconf.php
  ext_icon.png
  ext_localconf.php
  ext_tables.php
Labels: :heavy_check_mark: feature

#326 [FEATURE] 3D viewer selection
  Configuration/TypoScript/Plugins/kitodo.typoscript
  Resources/Private/Less/components/controls.less
  Resources/Private/Less/structure.less
  Resources/Private/Partials/Submenu.html
  Resources/Public/Css/allStyles.css
  Resources/Public/Css/webStyles.css
Labels: :heavy_check_mark: feature

#341 [IMPROVEMENT] Use slub repository branches for Docker image
  .github/workflows/build-test-publish.yml
Labels: :link: dependency

#342 [MAINTENANCE] Fix workflow for build, test and publish
  .github/workflows/build-test-publish.yml
Labels: 🛠️ maintenance

#343 [MAINTENANCE] Deploy documentation only if repository has GitHub pages
  .github/workflows/documentation.yml
Labels: 🛠️ maintenance

#335 [FEATURE] METS application profile validation
  .github/workflows/tests.yml
  .gitignore
  Build/Test/UnitTests.xml
  Build/Test/docker-compose.yml
  Build/Test/runTests.sh
  Classes/Common/ValidationHelper.php
  Classes/Validation/AbstractDomDocumentValidator.php
  Classes/Validation/ApplicationProfileValidationStack.php
  Classes/Validation/Common/DomNodeListValidator.php
  Classes/Validation/Common/DomNodeValidator.php
  Classes/Validation/DomDocumentUrlExistenceValidator.php
  Classes/Validation/DvMetadataValidator.php
  Classes/Validation/Mets/AdministrativeMetadataValidator.php
  Classes/Validation/Mets/DescriptiveMetadataValidator.php
  Classes/Validation/Mets/DigitalRepresentationValidator.php
  Classes/Validation/Mets/LinkingLogicalPhysicalStructureValidator.php
  Classes/Validation/Mets/LogicalStructureValidator.php
  Classes/Validation/Mets/PhysicalStructureValidator.php
  Configuration/TypoScript/Plugins/kitodo.typoscript
  Tests/Fixtures/mets.xml
  Tests/Unit/Validation/AbstractDomDocumentValidatorTest.php
  Tests/Unit/Validation/DomDocumentUrlExistenceValidatorTest.php
  Tests/Unit/Validation/DvMetadataValidatorTest.php
  Tests/Unit/Validation/Mets/AdministrativeMetadataValidatorTest.php
  Tests/Unit/Validation/Mets/DescriptiveMetadataValidatorTest.php
  Tests/Unit/Validation/Mets/DigitalRepresentationValidatorTest.php
  Tests/Unit/Validation/Mets/LinkingLogicalPhysicalStructureValidatorTest.php
  Tests/Unit/Validation/Mets/LogicalStructureValidatorTest.php
  Tests/Unit/Validation/Mets/PhysicalStructureValidatorTest.php
  composer.json
Labels: :heavy_check_mark: feature
